apiVersion: v1
kind: Service
metadata:
  name: snake-service
spec:
  type: NodePort
  selector:
    app: snake-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
